/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package manager;
import java.io.IOException;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;
import manager.controller.UserManagementController;

public class App extends Application {
    private Stage primaryStage;

    private static final int MIN_HEIGHT = 400;
    private static final int MIN_WIDTH = 500;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        this.primaryStage = primaryStage;
		this.primaryStage.setTitle("White board server management");
		initRootLayout();
    }

    private void initRootLayout() throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("Mangement.fxml"));
        GridPane root = fxmlLoader.load();
        UserManagementController umc = fxmlLoader.<UserManagementController>getController();
        // init umc

        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.setMinHeight(MIN_HEIGHT);
        primaryStage.setMinWidth(MIN_WIDTH);
        primaryStage.setOnCloseRequest(e->{
            Platform.exit();
            System.exit(0);
        });
        primaryStage.show();
    }
}
